<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.2.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'enquiries@rmdatasolutions.com.au',
		'to' => 'enquiries@rmdatasolutions.com.au'
	),
	'fields' => array(
		'custom_U445' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Company Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Company Name\' is required.'
			)
		),
		'custom_U506' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Primary Colour',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Primary Colour\' is required.'
			)
		),
		'custom_U523' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Secondary Colour',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Secondary Colour\' is required.'
			)
		),
		'custom_U539' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Style of Logo (Styles Below)',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Style of Logo (Styles Below)\' is required.'
			)
		),
		'custom_U617' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Tertiary Colour',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Tertiary Colour\' is required.'
			)
		),
		'custom_U735' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'RSA',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U872' => array(
			'order' => 7,
			'type' => 'checkbox',
			'label' => 'Renderforest',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U884' => array(
			'order' => 8,
			'type' => 'checkbox',
			'label' => 'S Logo',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U896' => array(
			'order' => 9,
			'type' => 'checkbox',
			'label' => 'M & M Electrical',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U908' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'R.M Data Solutions',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U920' => array(
			'order' => 11,
			'type' => 'checkbox',
			'label' => 'Innovolt ELectric',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U993' => array(
			'order' => 12,
			'type' => 'checkbox',
			'label' => 'Excellium Electrical',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1005' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'Shannon Thomas Electrical',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U1017' => array(
			'order' => 14,
			'type' => 'checkbox',
			'label' => 'Building Construction',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Building Construction\' is required.'
			)
		),
		'custom_U1029' => array(
			'order' => 15,
			'type' => 'checkbox',
			'label' => 'Building Company',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Building Company\' is required.'
			)
		),
		'custom_U1041' => array(
			'order' => 16,
			'type' => 'checkbox',
			'label' => 'Yellow',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Yellow\' is required.'
			)
		),
		'custom_U1053' => array(
			'order' => 17,
			'type' => 'checkbox',
			'label' => 'Beyond Bricklaying',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Beyond Bricklaying\' is required.'
			)
		)
	)
);

process_form($form);
?>
